### PR TITLE
Nonempty homepage

### PR DESCRIPTION
**Pull request by aymanhab**
Populate start page of the OpenSim visualizer with useful contents, possibly links to online resources and/or recent news,

### CODE REVIEW

**Comment by aymanhab** [comment]
As of now this looks for a Welcome.html page in the wrorking directory on startup, and shows a blank page if not found. Eventually we can move the file into code once we're happy.

**Comment by aymanhab** [comment]
Can you do quick review here @chrisdembia Thanks. The Welcome.html file would be missing so no effect but Tom can populate and test and then we can incorporate into build system if separate file or move into code. Thanks

**Review by chrisdembia — COMMENTED** [review]
Neat idea. Is this supposed to be a temporary change?  I don't think it makes sense for the released version of OpenSim to load the contents of an HTML file in the current directory.

If this is to be part of the release, then the Welcome.html file should have a specified location in the installation, and should have a more specific name, like `OpenSimVisualizerWelcome.html`.

What exactly are you thinking of incorporating into ~CI~?

EDIT: Ah I think you meant CMake/Ant, not CI.

**Comment by aymanhab** [comment]
@chrisdembia No, this is temporary for Tom to try out the contents and workflow by adding his own welcome.html, then we'll absorb the contents into code so we have more control.

**Comment by chrisdembia** [comment]
Okay then this looks fine to me, as long as we remember to remove this change when Tom is done testing.  I didn't test anything though.

**Comment by aymanhab** [comment]
That's fine @chrisdembia as long as you don't see anything that stands out as wrong or negative, will get feedback from you and the team when built into master. Thanks

**Pull request merged**
